steps:
  - command: |
      echo "+++ :hammer: Building" && \
      echo 1 | ./infrablockchain_build.sh && \
      echo "--- :compression: Compressing build directory" && \
      tar -pczf build.tar.gz build/
    label: ":ubuntu: 18.04 Build"
    agents:
      - "queue=builder"
      - "role=linux-builder"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    artifact_paths: "build.tar.gz"
    timeout: 60
  - command: |
      echo "+++ :hammer: Building" && \
      echo 1 | ./infrablockchain_build.sh && \
      echo "--- :compression: Compressing build directory" && \
      tar -pczf build.tar.gz build/
    label: ":centos: Build"
    agents:
      - "queue=builder"
      - "role=linux-builder"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    artifact_paths: "build.tar.gz"
    timeout: 60

  - wait

  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 18.04 Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":ubuntu: 18.04 Tests"
    agents:
      - "queue=builder"
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    timeout: 60
  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 18.04 Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":ubuntu: 18.04 NP Tests"
    agents:
      - "queue=builder"
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    timeout: 60
  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -j8 -LE _tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":centos: Tests"
    agents:
      - "queue=builder"
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60
  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -L nonparallelizable_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":centos: NP Tests"
    agents:
      - "queue=builder"
      - "role=linux-tester"
    artifact_paths:
      - "mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60
