steps:
  - command: |
      echo "+++ :hammer: Building" && \
      echo 1 | ./yosemite_build.sh && \
      echo "--- :compression: Compressing build directory" && \
      tar -pczf build.tar.gz build/
    label: ":ubuntu: Build"
    agents:
    - "role=linux-builder"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    artifact_paths: "build.tar.gz"
    timeout: 60

  - command: |
      echo "+++ :hammer: Building" && \
      echo 1 | ./yosemite_build.sh && \
      echo "--- :compression: Compressing build directory" && \
      tar -pczf build.tar.gz build/
    label: ":centos: Build"
    agents:
    - "role=linux-builder"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    artifact_paths: "build.tar.gz"
    timeout: 60

  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":ubuntu: Tests"
    agents:
    - "role=linux-tester"
    artifact_paths:
    - "mongod.log"
    - "build/genesis.json"
    - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60

  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -LE long_running_tests --output-on-failure
    retry:
      automatic:
        limit: 1
    label: ":centos: Tests"
    agents:
    - "role=linux-tester"
    artifact_paths:
    - "mongod.log"
    - "build/genesis.json"
    - "build/config.ini"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60
