steps:
  - command: |
      echo "+++ :hammer: Building" && \
      echo 1 | ./yosemite_build.sh && \
      echo "--- :compression: Compressing build directory" && \
      tar -pczf build.tar.gz build/ && \
      echo "--- :wastebasket: Cleaning build directory" && \
      buildkite-agent artifact upload "build.tar.gz" && \
      git clean -fxdq
    label: ":ubuntu: Build"
    agents:
    - "role=linux-builder"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60

  - command: |
      echo "+++ :hammer: Building" && \
      echo 1 | ./eosio_build.sh && \
      echo "--- :compression: Compressing build directory" && \
      tar -pczf build.tar.gz build/ && \
      echo "--- :wastebasket: Cleaning build directory" && \
      buildkite-agent artifact upload "build.tar.gz" && \
      git clean -fxdq
    label: ":centos: Build"
    agents:
    - "role=linux-builder"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60

  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -LE long_running_tests --output-on-failure && \
      cd .. && \
      buildkite-agent artifact upload "mongod.log" && \
      buildkite-agent artifact upload "build/genesis.json" && \
      buildkite-agent artifact upload "build/config.ini" && \
      rm -rf /data/job/*
    retry:
      automatic:
        limit: 1
    label: ":ubuntu: Tests"
    agents:
    - "role=linux-tester"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60

  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
      buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
      tar -zxf build.tar.gz && \
      echo "--- :m: Starting MongoDB" && \
      $(which mongod) --fork --logpath "$(pwd)"/mongod.log && \
      echo "+++ :microscope: Running tests" && \
      cd /data/job/build && ctest -LE long_running_tests --output-on-failure&& \
      cd .. && \
      buildkite-agent artifact upload "mongod.log" && \
      buildkite-agent artifact upload "build/genesis.json" && \
      buildkite-agent artifact upload "build/config.ini" && \
      rm -rf /data/job/*
    retry:
      automatic:
        limit: 1
    label: ":centos: Tests"
    agents:
    - "role=linux-tester"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60