version: "3"

services:
  yosemited:
    image: yosemitex/yosemite:latest
    command: /opt/yosemite/bin/yosemited.sh --data-dir /opt/yosemite/bin/data-dir -e --http-alias=yosemited:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: yosemited
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - yosemite-data-volume:/opt/yosemite/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keyos:
    image: yosemitex/yosemite:latest
    command: /opt/yosemite/bin/keyos --wallet-dir /opt/yosemite/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keyos:8900 --http-alias=localhost:8900
    hostname: keyos
    links:
      - yosemited
    volumes:
      - keyos-data-volume:/opt/yosemite/bin/data-dir
    stop_grace_period: 10m

volumes:
 yosemite-data-volume:
   external: true
 keyos-data-volume:
   external: true
