version: "3"

services:
  infra-node:
    image: infrablockchain/infrablockchain:latest
    command: /opt/infrablockchain/bin/infra-node.sh --data-dir /opt/infrablockchain/bin/data-dir -e --http-alias=infranode:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: infranode
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - infrablockchain-data-volume:/opt/infrablockchain/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  infra-keystore:
    image: infrablockchain/infrablockchain:latest
    command: /opt/infrablockchain/bin/infra-keystore --wallet-dir /opt/infrablockchain/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=infrakeystore:8900 --http-alias=localhost:8900
    hostname: infrakeystore
    links:
      - infra-node
    volumes:
      - infra-keystore-data-volume:/opt/infrablockchain/bin/data-dir
    stop_grace_period: 10m

volumes:
  infrablockchain-data-volume:
   external: true
 infra-keystore-data-volume:
   external: true
